import { BricsKnowledgeRecord } from './brics.types.js';

export const BRICS_SEED_DATA: BricsKnowledgeRecord[] = [
  // 1. INDIA (IN)
  {
    id: 'brics_in_01',
    country: 'IN',
    countryName: 'India',
    crop: 'Rice (Paddy)',
    topic: 'WATER_CONSERVATION',
    topicLabel: 'Water Conservation',
    practice: 'System of Rice Intensification (SRI) with Alternate Wetting and Drying (AWD)',
    summary: 'AWD irrigation reduces water consumption by up to 30% without sacrificing yield, while lowering methane emissions in flooded paddy soils.',
    impactMetric: '30% water savings, 25% lower methane emissions',
    source: 'Indian Council of Agricultural Research (ICAR)',
    sourceUrl: 'https://icar.org.in',
    sourceDate: '2024-03-15',
    tags: ['Water Efficiency', 'Methane Reduction', 'Paddy', 'Irrigation']
  },
  {
    id: 'brics_in_02',
    country: 'IN',
    countryName: 'India',
    crop: 'Wheat',
    topic: 'SOIL_HEALTH',
    topicLabel: 'Soil Health',
    practice: 'Zero-Tillage Wheat Sowing into Rice Residue (Happy Seeder)',
    summary: 'Direct sowing of wheat into standing paddy stubble eliminates open crop residue burning, preserves topsoil organic carbon, and reduces evaporation.',
    impactMetric: '+0.4% soil organic carbon over 3 seasons, 100% smoke reduction',
    source: 'Punjab Agricultural University (PAU)',
    sourceUrl: 'https://pau.edu',
    sourceDate: '2023-11-20',
    tags: ['Zero Tillage', 'Soil Organic Carbon', 'Residue Management', 'Wheat']
  },
  {
    id: 'brics_in_03',
    country: 'IN',
    countryName: 'India',
    crop: 'Cotton',
    topic: 'INTEGRATED_PEST_MGMT',
    topicLabel: 'Integrated Pest Management',
    practice: 'Push-Pull Bio-pest Management with Desmodium Intercropping',
    summary: 'Planting Desmodium between cotton rows repels bollworms while trap crops attract them away from main cash crop, eliminating synthetic pesticide over-reliance.',
    impactMetric: '45% reduction in pesticide chemical cost',
    source: 'Central Institute for Cotton Research (CICR)',
    sourceUrl: 'https://cicr.org.in',
    sourceDate: '2024-01-10',
    tags: ['Biological Control', 'Pest Management', 'Cotton', 'Intercropping']
  },

  // 2. BRAZIL (BR)
  {
    id: 'brics_br_01',
    country: 'BR',
    countryName: 'Brazil',
    crop: 'Soybean',
    topic: 'SOIL_HEALTH',
    topicLabel: 'Soil Health',
    practice: 'No-Till Direct Planting System (Plantio Direto) with Cover Crop Rotations',
    summary: 'Permanent soil cover with Brachiaria grass and millet prior to soybean planting stabilizes tropical soil temperature, prevents erosion, and boosts mycorrhizal activity.',
    impactMetric: '80% erosion reduction, +35% soil moisture retention',
    source: 'Embrapa Soja (Brazilian Agricultural Research Corporation)',
    sourceUrl: 'https://embrapa.br/soja',
    sourceDate: '2024-02-18',
    tags: ['No-Till', 'Cover Crops', 'Soybean', 'Erosion Control']
  },
  {
    id: 'brics_br_02',
    country: 'BR',
    countryName: 'Brazil',
    crop: 'Corn (Maize)',
    topic: 'AGROFORESTRY',
    topicLabel: 'Agroforestry & Crop-Livestock',
    practice: 'Integrated Crop-Livestock-Forestry System (ILPF)',
    summary: 'Combining Eucalyptus timber strips with intercropped maize and cattle pasture optimizes land utilization and sequesters carbon while protecting against heat waves.',
    impactMetric: 'Carbon neutral beef & grain certification, +22% overall land productivity',
    source: 'Embrapa Agropecuária Oeste',
    sourceUrl: 'https://embrapa.br',
    sourceDate: '2023-09-05',
    tags: ['Integrated System', 'ILPF', 'Agroforestry', 'Carbon Neutral']
  },
  {
    id: 'brics_br_03',
    country: 'BR',
    countryName: 'Brazil',
    crop: 'Sugarcane',
    topic: 'INTEGRATED_PEST_MGMT',
    topicLabel: 'Integrated Pest Management',
    practice: 'Trichogramma Galloi Wasp Parasitoid Release for Stem Borer Control',
    summary: 'Mass drone release of micro-wasps parasite eggs of sugarcane borer Diatraea saccharalis, replacing organophosphate sprays.',
    impactMetric: '92% biological pest reduction efficiency',
    source: 'CTC - Sugarcane Technology Center Brazil',
    sourceUrl: 'https://ctc.com.br',
    sourceDate: '2024-04-02',
    tags: ['Bio-control', 'Sugarcane', 'Drone Application', 'Pest Control']
  },

  // 3. RUSSIA (RU)
  {
    id: 'brics_ru_01',
    country: 'RU',
    countryName: 'Russia',
    crop: 'Wheat',
    topic: 'SOIL_HEALTH',
    topicLabel: 'Soil Health',
    practice: 'Chernozem Humus Preservation via Minimum-Till and Humic Acid Amendment',
    summary: 'Preserving black soil organic matter in southern steppe regions by combining reduced tillage with bio-humate soil conditioners derived from peat/lignite.',
    impactMetric: '+18% humic fraction retention, drought index resilience +25%',
    source: 'Russian Academy of Sciences (V.V. Dokuchaev Soil Science Institute)',
    sourceUrl: 'https://esoil.ru',
    sourceDate: '2023-10-12',
    tags: ['Chernozem Soil', 'Humic Acid', 'Minimum Till', 'Wheat']
  },
  {
    id: 'brics_ru_02',
    country: 'RU',
    countryName: 'Russia',
    crop: 'Sunflower',
    topic: 'CROP_DIVERSIFICATION',
    topicLabel: 'Crop Diversification',
    practice: 'Sunflower-Sainfoin Leguminous Strip Intercropping',
    summary: 'Alternating drought-tolerant sunflower belts with perennial nitrogen-fixing sainfoin improves soil nitrogen reserves and honeybee pollination activity.',
    impactMetric: '+30 kg/ha natural nitrogen fixation, +15% seed oil content',
    source: 'Timiryazev Agricultural Academy Moscow',
    sourceUrl: 'https://timacad.ru',
    sourceDate: '2024-01-25',
    tags: ['Legume Intercropping', 'Nitrogen Fixation', 'Sunflower', 'Pollination']
  },

  // 4. CHINA (CN)
  {
    id: 'brics_cn_01',
    country: 'CN',
    countryName: 'China',
    crop: 'Rice (Paddy)',
    topic: 'INTEGRATED_PEST_MGMT',
    topicLabel: 'Integrated Pest Management & Biodiversity',
    practice: 'Rice-Fish-Duck Symbiotic Co-Culture System',
    summary: 'Releasing ducks and fish into paddy fields naturally consumes planthoppers and weed seeds, while their droppings enrich soil fertility without chemical inputs.',
    impactMetric: '60% pesticide reduction, zero synthetic fertilizer needed in year 2+',
    source: 'Chinese Academy of Agricultural Sciences (CAAS)',
    sourceUrl: 'https://caas.cn',
    sourceDate: '2024-05-10',
    tags: ['Symbiotic Farming', 'Rice-Fish-Duck', 'Organic Soil', 'Paddy']
  },
  {
    id: 'brics_cn_02',
    country: 'CN',
    countryName: 'China',
    crop: 'Corn (Maize)',
    topic: 'WATER_CONSERVATION',
    topicLabel: 'Water Conservation',
    practice: 'Film Mulching with Drip Irrigation under Plastic (DIP)',
    summary: 'Biodegradable film mulching over micro-drip tapes reduces soil evaporation in semi-arid northern plains while keeping soil warm during early spring germination.',
    impactMetric: '40% irrigation water reduction, +18% yield in dry regions',
    source: 'China Agricultural University (CAU)',
    sourceUrl: 'https://cau.edu.cn',
    sourceDate: '2023-12-04',
    tags: ['Drip Irrigation', 'Mulching', 'Maize', 'Water Savings']
  },
  {
    id: 'brics_cn_03',
    country: 'CN',
    countryName: 'China',
    crop: 'Vegetables (General)',
    topic: 'CARBON_SEQUESTRATION',
    topicLabel: 'Carbon Sequestration & Soil Amending',
    practice: 'Straw Biochar Soil Conditioning in Intensive Vegetable Cropping',
    summary: 'Pyrolyzed crop straw biochar application locks carbon in soil for decades, increases cation exchange capacity (CEC), and reduces heavy metal bioavailability.',
    impactMetric: '2.5 t/ha CO2 equivalent sequestered, +28% CEC increase',
    source: 'Nanjing Agricultural University',
    sourceUrl: 'https://njau.edu.cn',
    sourceDate: '2024-02-28',
    tags: ['Biochar', 'Carbon Sequestration', 'Soil Amending', 'Vegetables']
  },

  // 5. SOUTH AFRICA (ZA)
  {
    id: 'brics_za_01',
    country: 'ZA',
    countryName: 'South Africa',
    crop: 'Citrus',
    topic: 'WATER_CONSERVATION',
    topicLabel: 'Water Conservation',
    practice: 'Under-Canopy Organic Woodchip Mulching with Sap Flow Monitoring',
    summary: 'Applying thick acacia woodchip mulch beneath citrus trees prevents solar heat soil crusting, combined with real-time trunk sap flow sensors for precision pulse irrigation.',
    impactMetric: '35% evaporation reduction, +20% fruit pack-out rate',
    source: 'Citrus Research International (CRI South Africa)',
    sourceUrl: 'https://cri-online.co.za',
    sourceDate: '2024-03-20',
    tags: ['Precision Irrigation', 'Mulching', 'Citrus', 'Sensors']
  },
  {
    id: 'brics_za_02',
    country: 'ZA',
    countryName: 'South Africa',
    crop: 'Wheat',
    topic: 'CROP_DIVERSIFICATION',
    topicLabel: 'Crop Diversification',
    practice: 'Conservation Agriculture (CA) Med-Pasture Rotation in Winter Rainfall Region',
    summary: 'Rotating dryland winter wheat with annual medic/clover pastures restores soil nitrogen, disrupts grass weed cycles, and yields livestock forage.',
    impactMetric: '50 kg/ha synthetic N saved, weed herbicide resistance breakdown',
    source: 'Western Cape Department of Agriculture',
    sourceUrl: 'https://elsenburg.com',
    sourceDate: '2023-08-14',
    tags: ['Conservation Agriculture', 'Crop Rotation', 'Wheat', 'Pasture']
  }
];
